52 display dynamic weather image
nashvillefcc/local-weather-app pull request #54
Opened 2019-11-17 08:36 UTC by jhadams82

builds a url to the weather icon for user's current position

Closes #52

2019-11-24 22:52 UTC, MoribundMedium requested changes
Code doesn't work. Do we need to merge #53 or Develop into this one?

Additionally, while the static image added in #53 provides a good place to drop in the dynamic image, we're going to need to remove the static image that's currently there or add in a placeholder image. Can't be displaying a "rainy" image if it's not raining, you know? Even if it does get overwritten a moment later.

2019-11-24 22:52 UTC, MoribundMedium commented on code.js
> +      console.log(res);
Please remove `console.log()` statements before merging.

2019-11-24 22:52 UTC, MoribundMedium commented on code.js
> +      console.log(`iconUrl: ${iconUrl}`);
I'd recommend moving this block of code to a helper function, then calling it from within `getTheWeather()`. At the same time, refactor L46-L48 into a helper function too. We don't want to get the logic from two different functions mixed up together.

2019-11-25 01:24 UTC, jhadams82 commented
requested changes made, try it now

2019-11-25 03:04 UTC, MoribundMedium approved these changes
Legiiiiiiiit

Code is nice and clean and simple. I dig it.

2019-11-25 03:05 UTC, merged